In [1]:
import pandas as pd
import numpy as np
import time

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsClassifier, NearestNeighbors

In [2]:
df = pd.read_csv("Dataset\\cleaned_title_netflix_dataset.csv")
ori_df = pd.read_csv('Dataset\\cleaned_title_netflix_dataset.csv')

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7787 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7787 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB

In [4]:
drop_features = ['show_id', 'date_added', 'duration', 'description']

df = df.drop(columns=drop_features)

df.head()

,type,title,director,cast,country,release_year,rating,listed_in
0,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,2020,TV-MA,"International TV Shows, TV Dramas, TV Sci-Fi &..."
1,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,2016,TV-MA,"Dramas, International Movies"
2,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,2011,R,"Horror Movies, International Movies"
3,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,2009,PG-13,"Action & Adventure, Independent Movies, Sci-Fi..."
4,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,2008,PG-13,Dramas

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          7787 non-null   object
 1   title         7787 non-null   object
 2   director      5398 non-null   object
 3   cast          7069 non-null   object
 4   country       7280 non-null   object
 5   release_year  7787 non-null   int64
 6   rating        7787 non-null   object
 7   listed_in     7787 non-null   object
dtypes: int64(1), object(7)
memory usage: 486.8+ KB

In [6]:
df = df.dropna()

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4812 entries, 1 to 7783
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          4812 non-null   object
 1   title         4812 non-null   object
 2   director      4812 non-null   object
 3   cast          4812 non-null   object
 4   country       4812 non-null   object
 5   release_year  4812 non-null   int64
 6   rating        4812 non-null   object
 7   listed_in     4812 non-null   object
dtypes: int64(1), object(7)
memory usage: 338.3+ KB

In [7]:
def unique_value(feature):
    unique = []
    for val in df[feature]:
        if ',' in val:
            ftr = val.split(',')
            unique.extend(ftr)
        else:
            unique.append(val)
    
    unique = pd.Series(unique)
    unique = list(unique.apply(lambda x: x.strip()))
    
    ftr, counts = np.unique(unique, return_counts=True)

    counts = pd.DataFrame(data={'ftr':ftr,
                                'counts':counts}).sort_values('counts', ascending=False)

    print(f"There are {counts['ftr'].shape[0]} {feature}")

In [8]:
unique_value('cast')
unique_value('country')
unique_value('listed_in')
unique_value('director')

There are 23222 cast
There are 104 country
There are 42 listed_in
There are 3963 director

In [9]:
def unique_value_cl(feature, rng_cl):
    unique = []

    value = df[feature].str.split(',', expand=True).loc[:, :rng_cl]
    value = value.fillna('missing')
    for column in value.columns:
        value[column].apply(lambda x: unique.append(x))

    unique = pd.Series(unique)
    unique = list(unique.apply(lambda x: x.strip()))
    
    val, counts = np.unique(unique, return_counts=True)

    counts = pd.DataFrame(data={'value':val,
                                'counts':counts}).sort_values('counts', ascending=False)

    print(f"There are {counts['value'].shape[0]} {feature}")

In [10]:
unique_value_cl('cast', 4)
unique_value_cl('country', 1)
unique_value_cl('director', 1)
unique_value_cl('listed_in', 1)

There are 13378 cast
There are 94 country
There are 3855 director
There are 41 listed_in

In [11]:
def null_percent_cl(feature, rng_cl):
    ftr = df[feature].str.split(',', expand=True).loc[:, :rng_cl]
    for column in ftr.columns:
        thres = ftr.loc[:, column].isnull().sum()
        print(f"There are {round((thres/ftr.shape[0]) * 100, 2)} null percent in {feature} column {column}")
    print('\n-------')

In [12]:
null_percent_cl('cast', 3)
null_percent_cl('country', 0)
null_percent_cl('director', 0)
null_percent_cl('listed_in', 0)

There are 0.0 null percent in cast column 0
There are 11.41 null percent in cast column 1
There are 13.2 null percent in cast column 2
There are 14.96 null percent in cast column 3

-------
There are 0.0 null percent in country column 0

-------
There are 0.0 null percent in director column 0

-------
There are 0.0 null percent in listed_in column 0

-------

In [13]:
unique_value_cl('cast', 3)
unique_value_cl('country', 0)
unique_value_cl('director', 0)
unique_value_cl('listed_in', 0)

There are 10982 cast
There are 72 country
There are 3531 director
There are 32 listed_in

In [14]:
def transformed_cl(feature, rng_cl):
    unique = []

    ftr = df[feature].str.split(',', expand=True).loc[:, :rng_cl]
    ftr = ftr.fillna('missing')
    for column in ftr.columns:
        ftr[column].apply(lambda x: unique.append(x))

    unique = pd.Series(unique)
    unique = list(unique.apply(lambda x: x.strip()))
    
    unique = np.unique(unique)
    ftr = pd.DataFrame(columns=unique)
    
    ind = []
    for val in df[feature]:
        trans = []
        for column in ftr.columns:
            if column in val:
                trans.append(1)
            else:
                trans.append(0)
        ind.append(trans)
        
    columns = []
    for unq in unique:
        columns.append(f"{unq}_{feature}")
    
    return pd.DataFrame(ind, columns=columns)

In [15]:
def transformed(feature):
    unique = df[feature].value_counts().index
    ftr = pd.DataFrame(columns=unique)
    
    ind = []
    for val in df[feature]:
        trans = []
        for column in ftr.columns:
            if column == val:
                trans.append(1)
            else:
                trans.append(0)
        ind.append(trans)
        
    columns = []
    for unq in unique:
        columns.append(f"{unq}_{feature}")
        
    return pd.DataFrame(ind, columns=columns)

In [16]:
start = time.time()

casts = transformed_cl('cast', 3).reset_index(drop=True)
directors = transformed_cl('director', 0).reset_index(drop=True)
countries = transformed_cl('country', 0).reset_index(drop=True)
genres = transformed_cl('listed_in', 0).reset_index(drop=True)

types = transformed('type').reset_index(drop=True)
ratings = transformed('rating').reset_index(drop=True)

print(f'Finish : {time.time() - start}')

Finish : 49.01999378204346

In [17]:
df = df[['title', 'release_year']].reset_index(drop=True)

df = pd.concat([df, casts, directors, genres, ratings, countries, types], axis=1)

df.shape

(4812, 14635)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Columns: 14635 entries, title to TV Show_type
dtypes: int64(14634), object(1)
memory usage: 537.3+ MB

# Modelling

In [19]:
ori_df = ori_df.dropna()
ori_df = ori_df.reset_index(drop=True)

In [20]:
X = df.drop(['title'], axis=1)
y = df['title']

In [21]:
neigh = NearestNeighbors(algorithm='brute')

neigh.fit(X)

NearestNeighbors(algorithm='brute')

In [22]:
def find_movies(title):
    if title in df['title'].values:
        x = df[df['title'] == title].drop(columns=['title'])
        distances, movies = neigh.kneighbors(x, 6, return_distance=True)
        
        
        result = ori_df.copy()
        result = result.iloc[movies[0]]
        result['distance'] = distances[0]
        
        return result
    else:
        print("Title is not in dataset")

In [23]:
find_movies('The Conjuring')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,distance
3888,s6243,Movie,The Conjuring,James Wan,"Vera Farmiga, Patrick Wilson, Lili Taylor, Ron...",United States,"January 8, 2018",2013,R,112 min,"Horror Movies, Thrillers","Based on true events, this spine-chiller tells...",0.000000
975,s1531,Movie,Creep,Patrick Brice,"Mark Duplass, Patrick Brice",United States,"July 14, 2015",2014,R,78 min,"Horror Movies, Independent Movies, Thrillers",When a cash-strapped videographer takes a job ...,3.605551
860,s1313,Movie,Chernobyl Diaries,Bradley Parker,"Ingrid Bolsø Berdal, Dimitri Diatchenko, Olivi...",United States,"August 1, 2018",2012,R,88 min,"Horror Movies, Thrillers",A group of kids takes an illegal tour through ...,3.741657
2116,s3345,Movie,Kevin Hart: Let Me Explain,"Leslie Small, Tim Story",Kevin Hart,United States,"July 13, 2018",2013,R,75 min,Stand-Up Comedy,Philadelphia funnyman Kevin Hart takes the sta...,3.741657
409,s592,Movie,"As Above, So Below",John Erick Dowdle,"Perdita Weeks, Ben Feldman, Edwin Hodge, Franç...",United States,"September 16, 2018",2014,R,93 min,"Horror Movies, Thrillers",A beautiful tomb raider and her crew hunt for ...,3.741657
3921,s6294,Movie,The Devil Inside,William Brent Bell,"Fernanda Andrade, Simon Quarterman, Evan Helmu...",United States,"November 20, 2019",2012,R,84 min,"Horror Movies, Thrillers","At once spooky and grisly, this thriller follo...",3.741657

In [24]:
find_movies('Avengers: Infinity War')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,distance
437,s636,Movie,Avengers: Infinity War,"Anthony Russo, Joe Russo","Robert Downey Jr., Josh Brolin, Mark Ruffalo, ...",United States,"December 25, 2018",2018,PG-13,150 min,"Action & Adventure, Sci-Fi & Fantasy",Superheroes amass to stop intergalactic sociop...,0.000000
3394,s5440,Movie,Scorpion King 5: Book of Souls,Don Michael Paul,"Zach McGowan, Pearl Thusi, Nathan Jones, Peter...",United States,"October 23, 2018",2018,PG-13,102 min,"Action & Adventure, Sci-Fi & Fantasy",The Scorpion King joins forces with a Nubian p...,5.656854
519,s764,Movie,Bathtubs Over Broadway,Dava Whisenant,Steve Young,United States,"May 9, 2019",2018,PG-13,87 min,"Documentaries, Music & Musicals",A comedy writer for David Letterman unearths a...,5.744563
1902,s3047,Movie,IO,Jonathan Helpert,"Margaret Qualley, Anthony Mackie, Danny Huston",United States,"January 18, 2019",2019,TV-14,96 min,"Dramas, Sci-Fi & Fantasy",As a young scientist searches for a way to sav...,5.744563
647,s960,Movie,Black Panther,Ryan Coogler,"Chadwick Boseman, Michael B. Jordan, Lupita Ny...",United States,"September 4, 2018",2018,PG-13,135 min,"Action & Adventure, Sci-Fi & Fantasy","T'Challa, the superpowered new leader of the h...",5.744563
3279,s5271,Movie,"Ron White: If You Quit Listening, I'll Shut Up",Tom Forrest,Ron White,United States,"October 16, 2018",2018,TV-MA,63 min,Stand-Up Comedy,Ron “Tater Salad” White dishes out his signatu...,5.830952

In [25]:
find_movies("Insidious")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,distance
1886,s3020,Movie,Insidious,James Wan,"Patrick Wilson, Rose Byrne, Lin Shaye, Ty Simp...","United States, Canada, United Kingdom","May 9, 2019",2010,PG-13,103 min,"Horror Movies, Thrillers","Hoping to leave their haunted house behind, a ...",0.000000
388,s563,Movie,Apollo 18,Gonzalo López-Gallego,"Warren Christie, Lloyd Owen, Ryan Robbins, Mic...","United States, Canada","March 9, 2019",2011,PG-13,87 min,"Horror Movies, Sci-Fi & Fantasy, Thrillers","This sci-fi thriller suggests that Apollo 17, ...",4.000000
2338,s3738,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,TV-MA,84 min,Movies,Emmy-winning comedy writer Louis C.K. brings h...,4.000000
2173,s3427,Movie,Knowing,Alex Proyas,"Nicolas Cage, Chandler Canterbury, Rose Byrne,...","United States, United Kingdom, Australia","October 1, 2019",2009,PG-13,121 min,"Sci-Fi & Fantasy, Thrillers",An MIT astrophysics professor and his son unea...,4.123106
3476,s5561,Movie,Shelter,"Måns Mårlind, Björn Stein","Julianne Moore, Jonathan Rhys Meyers, Jeffrey ...",United States,"December 29, 2017",2010,R,112 min,"Horror Movies, Thrillers",A forensic psychiatrist has to think outside t...,4.123106
618,s916,Movie,Bill Burr: Let It Go,Shannon Hartman,Bill Burr,United States,"November 10, 2017",2010,NR,65 min,Stand-Up Comedy,The musings of comedian Bill Burr are let loos...,4.242641

In [26]:
find_movies("Dilan 1990")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,distance
1122,s1763,Movie,Dilan 1990,"Fajar Bustomi, Pidi Baiq","Vanesha Prescilla, Iqbaal Ramadhan, Debo Andry...",Indonesia,"May 14, 2020",2018,TV-14,109 min,"Dramas, International Movies, Romantic Movies","At a Bandung high school, charming and rebelli...",0.000000
1123,s1764,Movie,Dilan 1991,"Fajar Bustomi, Pidi Baiq","Iqbaal Ramadhan, Vanesha Prescilla, Ira Wibowo...",Indonesia,"May 14, 2020",2019,TV-14,118 min,"Dramas, International Movies, Romantic Movies",Dilan's involvement in the motorbike gang impe...,2.645751
2566,s4099,Movie,Milea,"Fajar Bustomi, Pidi Baiq","Iqbaal Ramadhan, Vanesha Prescilla, Ira Wibowo...",Indonesia,"June 13, 2020",2020,TV-14,100 min,"Dramas, International Movies, Romantic Movies","Years after his teen romance with Milea, a now...",3.000000
4385,s7048,Movie,This Earth of Mankind,Hanung Bramantyo,"Iqbaal Ramadhan, Mawar de Jongh, Sha Ine Febri...",Indonesia,"April 23, 2020",2019,TV-14,180 min,"Dramas, International Movies",A Javanese royal and half-Dutch woman fall in ...,3.316625
1226,s1932,Movie,Eggnoid: Love & Time Portal,Naya Anindita,"Morgan Oey, Sheila Dara, Luna Maya, Kevin Juli...",Indonesia,"December 17, 2020",2019,TV-14,102 min,"Dramas, International Movies, Romantic Movies",Sent from the future to look after a lonely gi...,3.464102
3044,s4858,Movie,Pihu,Vinod Kapri,Pihu Myra Vishwakarma,India,"June 15, 2019",2018,TV-14,90 min,"Dramas, Independent Movies, International Movies",A two-year-old must fend for herself when her ...,3.464102

In [27]:
find_movies("Rudy Habibie")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,distance
3293,s5294,Movie,Rudy Habibie,Hanung Bramantyo,"Reza Rahadian, Chelsea Islan, Dian Nitami, Ind...",Indonesia,"January 28, 2019",2016,TV-14,143 min,"Dramas, International Movies",A biopic that explores the hardships and trium...,0.000000
3685,s5921,Movie,Surga Yang Tak Dirindukan 2,"Hanung Bramantyo, Meisa Felaroze","Fedi Nuril, Raline Shah, Laudya Cynthia Bella,...",Indonesia,"January 28, 2019",2017,TV-14,119 min,"Dramas, Faith & Spirituality, International Mo...","In this sequel to the award-winning 2015 film,...",3.000000
67,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,"January 5, 2019",2016,TV-PG,124 min,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...,3.162278
840,s1275,Movie,Chaotic Love Poems,Garin Nugroho,"Chicco Jerikho, Pevita Pearce",Indonesia,"January 5, 2019",2016,TV-14,86 min,"Dramas, International Movies, Romantic Movies","Spanning the 1970s, ‘80s and ‘90s, this lyrica...",3.316625
4593,s7409,Movie,Verses of Love 2,Guntur Soeharjanto,"Fedi Nuril, Tatjana Saphira, Dewi Sandra, Chel...",Indonesia,"October 18, 2019",2017,TV-14,127 min,"Dramas, Faith & Spirituality, International Mo...","Now a lecturer in Edinburgh, Fahri tries to be...",3.605551
3572,s5711,Movie,Sometimes,Priyadarshan,"Prakash Raj, Shreya Reddy, Ashok Selvan",India,"May 1, 2018",2016,TV-14,101 min,"Dramas, International Movies",Seven strangers anxiously waiting for their HI...,3.605551

In [28]:
find_movies('#FriendButMarried')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,distance
21,s32,Movie,#FriendButMarried,Rako Prijanto,"Adipati Dolken, Vanesha Prescilla, Rendi Jhon,...",Indonesia,"May 21, 2020",2018,TV-G,102 min,"Dramas, International Movies, Romantic Movies","Pining for his high school crush for years, a ...",0.000000
22,s33,Movie,#FriendButMarried 2,Rako Prijanto,"Adipati Dolken, Mawar de Jongh, Sari Nila, Von...",Indonesia,"June 28, 2020",2020,TV-G,104 min,"Dramas, International Movies, Romantic Movies",As Ayu and Ditto finally transition from best ...,3.605551
1122,s1763,Movie,Dilan 1990,"Fajar Bustomi, Pidi Baiq","Vanesha Prescilla, Iqbaal Ramadhan, Debo Andry...",Indonesia,"May 14, 2020",2018,TV-14,109 min,"Dramas, International Movies, Romantic Movies","At a Bandung high school, charming and rebelli...",3.741657
1467,s2339,Movie,Galih dan Ratna,Lucky Kuswandi,"Refal Hady, Sheryl Sheinafia, Ayu Dyah Pasha, ...",Indonesia,"September 15, 2018",2017,TV-PG,111 min,"Dramas, International Movies, Romantic Movies",Sparks fly between the new girl at school and ...,3.741657
2303,s3665,Movie,Little Miss Sumo,Matt Kay,Hiyori Kon,United Kingdom,"October 28, 2019",2018,TV-G,20 min,"Documentaries, International Movies, Sports Mo...",In an ancient sport traditionally reserved for...,3.872983
3076,s4917,Movie,Posesif,Edwin,"Putri Marino, Adipati Dolken, Gritte Agatha, C...",Indonesia,"January 1, 2020",2017,TV-MA,102 min,"Dramas, International Movies, Romantic Movies",A student diver risks her scholastic future an...,3.872983

In [29]:
find_movies("Creep")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,distance
975,s1531,Movie,Creep,Patrick Brice,"Mark Duplass, Patrick Brice",United States,"July 14, 2015",2014,R,78 min,"Horror Movies, Independent Movies, Thrillers",When a cash-strapped videographer takes a job ...,0.000000
4176,s6723,Movie,The One I Love,Charlie McDowell,"Mark Duplass, Elisabeth Moss, Ted Danson",United States,"May 30, 2019",2014,R,91 min,"Comedies, Dramas, Independent Movies",Confronted with the potential end of their mar...,3.000000
409,s592,Movie,"As Above, So Below",John Erick Dowdle,"Perdita Weeks, Ben Feldman, Edwin Hodge, Franç...",United States,"September 16, 2018",2014,R,93 min,"Horror Movies, Thrillers",A beautiful tomb raider and her crew hunt for ...,3.000000
43,s66,Movie,13 Sins,Daniel Stamm,"Mark Webber, Rutina Wesley, Devon Graye, Tom B...",United States,"January 13, 2019",2014,R,93 min,"Horror Movies, Thrillers",A man agrees to appear on a game show with a $...,3.162278
4558,s7347,Movie,Unfriended,Levan Gabriadze,"Shelley Hennig, Moses Storm, Renee Olstead, Wi...","United States, Russia","October 16, 2020",2014,R,83 min,"Horror Movies, Thrillers",Six teens whose cyberbullying drove their clas...,3.316625
2116,s3345,Movie,Kevin Hart: Let Me Explain,"Leslie Small, Tim Story",Kevin Hart,United States,"July 13, 2018",2013,R,75 min,Stand-Up Comedy,Philadelphia funnyman Kevin Hart takes the sta...,3.316625

In [30]:
find_movies("Creep 2")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,distance
976,s1532,Movie,Creep 2,Patrick Brice,"Mark Duplass, Desiree Akhavan, Karan Soni",United States,"December 23, 2017",2017,TV-MA,80 min,"Horror Movies, Independent Movies, Thrillers",A video artist finds the perfect character for...,0.000000
3753,s6033,Movie,Terrifier,Damien Leone,"Jenna Kanell, Samantha Scaffidi, David Howard ...",United States,"September 1, 2018",2017,TV-MA,84 min,"Horror Movies, Independent Movies, Thrillers","On Halloween night, inside a dilapidated apart...",3.000000
2337,s3737,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,TV-MA,74 min,Movies,"Louis C.K. muses on religion, eternal love, gi...",3.000000
3863,s6201,Movie,The Carter Effect,Sean Menard,Vince Carter,United States,"May 1, 2018",2017,TV-MA,60 min,"Documentaries, Sports Movies",Featuring eight-time NBA All-Star Vince Carter...,3.162278
4520,s7283,Movie,Twinsanity,Buz Wallick,"Karissa Strain, Katie Strain, Yves Bright, Ang...",United States,"March 15, 2019",2018,TV-MA,86 min,"Horror Movies, Independent Movies, Thrillers",When a yoga enthusiast begins to pull away fro...,3.162278
1088,s1716,Movie,Desolation,Sam Patton,"Jaimi Paige, Alyshia Ochse, Toby Nichols, Clau...",United States,"May 8, 2018",2017,TV-MA,76 min,"Horror Movies, Thrillers","Along with her son and best friend, a grieving...",3.162278

In [31]:
find_movies("Single")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,distance
3519,s5629,Movie,Single,Raditya Dika,"Raditya Dika, Annisa Rawles, Chandra Liow, Pan...",Indonesia,"September 28, 2018",2015,TV-PG,127 min,"Comedies, International Movies, Romantic Movies","Unemployed and immature, a somewhat pathetic b...",0.000000
840,s1275,Movie,Chaotic Love Poems,Garin Nugroho,"Chicco Jerikho, Pevita Pearce",Indonesia,"January 5, 2019",2016,TV-14,86 min,"Dramas, International Movies, Romantic Movies","Spanning the 1970s, ‘80s and ‘90s, this lyrica...",3.464102
1430,s2282,Movie,French Toast,"Paul Krüger, Anél Stolp","Lika Berning, Thierry Ballarin, Deon Lotz, Hel...",South Africa,"February 12, 2020",2015,TV-PG,86 min,"Comedies, International Movies, Romantic Movies",With only her mother's diary and a locket as c...,3.605551
2362,s3782,Movie,Love You... Love You Not,Sridhar Jetty,"Chelsea Islan, Hamish Daud, Miller Khan, Kemal...",Indonesia,"January 5, 2019",2015,TV-14,115 min,"Comedies, International Movies, Romantic Movies",A love triangle gets complicated when a female...,3.605551
3752,s6028,Movie,Terra,"Yann Arthus-Bertrand, Michael Pitiot",Vanessa Paradis,France,"May 1, 2016",2015,TV-PG,98 min,"Documentaries, International Movies",This visually arresting documentary essay refl...,3.605551
4686,s7566,Movie,What the Jatt!!,Saket Behl,"Harish Verma, Isha Rikhi, Vipul Roy, Binnu Dhi...",India,"October 1, 2018",2015,TV-PG,140 min,"Comedies, International Movies, Romantic Movies",A peasant from Punjab and his best friend pose...,3.741657